export enum Role {
  ADMIN = "ADMIN",
  TEACHER = "TEACHER",
  STUDENT = "STUDENT",
  OTHER_EMPLOYEE = "OTHER_EMPLOYEE",
}

export type DB_User = {
  ID: number;
  USERNAME: string;
  PASSWORD: string;
};

export type User = {
  ID: number;
  USERNAME: string;
  ROLE: Role;
  PHOTO_URL: string;
  PUBLIC_NAME: string;
};

//Make type for teachers and students
export type Teacher = {
  TEACHER_ID: number;
  EMPLOYEE_ID: number;
  USERNAME: string;
  PASSWORD: string;
  PHOTO_URL: string;
  PUBLIC_NAME: string;
};

export type Admin = {
  ADMIN_ID: number;
  EMPLOYEE_ID: number;
  USERNAME: string;
  PASSWORD: string;
  PHOTO_URL: string;
  PUBLIC_NAME: string;
};

// Generated by https://quicktype.io

export interface TeacherInfo {
  TEACHER_ID: number;
  EMPLOYEE_ID: number;
  PUBLIC_NAME: string;
  USERNAME: string;
  PHOTO_URL: string;
  PASSWORD: string;
  SUBJECTS: string;
  FIRSTNAME: string;
  LASTNAME: string;
  EMAIL: string;
  HIRED_AT: string;
  ROLE: string;
}

export type Student = {
  STUDENT_ID: number;
  USERNAME: string;
  PASSWORD: string;
  PHOTO_URL: string;
  PUBLIC_NAME: string;
};

export interface ClassAssignment {
  ASSIGNMENT_NAME: string;
  ASSIGNMENT_DESCRIPTION: string;
  ASSIGNMENT_DEADLINE: string;
  ASSIGNMENT_FILE: string;
  ASSIGNMENT_SUBJECT: string;
  ASSIGNMENT_GRADE_TYPE: string;
}

export interface StudentAssignmentFile {
  STUDENT_FILE_ID: string;
  STUDENT_TASK_ID: string;
  STUDENT_ID: number;
  FILE_NAME: string;
  FILE_URL: string;
  UPLOADED_AT: string;
}

export type StudentAssignmentUI = {
  STATUS: string;
  STUDENT_TASK_ID: number;
  ASSIGNMENT_ID: number;
  TEACHER_ID: number;
  ASSIGNMENT_NAME: string;
  GRADE_TYPE: string;
  SUBJECT: string;
  CLASS_ID: number;
  GRADE: string;
  DEADLINE: Date;
  WORK_FILES: StudentAssignmentFile[];
  ASSIGNMENT_FILES: AssignmentFile[];
};

export type SSFile = {
  FILE_NAME: string;
  FILE_URL: string;
  UPLOADED_AT: string;
};

export type SSFileState = {
  FILE_NAME: string;
  FILE_URL: string;
  UPLOADED_AT: string;
  PATH_IN_DESKTOP: string;
};

export interface AssignmentFile {
  FILE_ID: number;
  ASSIGNMENT_ID: number;
  TEACHER_ID: number;
  FILE_NAME: string;
  FILE_URL: string;
  UPLOADED_AT: string;
}
export interface StudentAssignment {
  STUDENT_TASK_ID: string;
  ASSIGNMENT_ID: string;
  STUDENT_ID: string;
  GRADE: string;
  STATUS: string;
  WORK_FILES: StudentAssignmentFile[];
  ASSIGNMENT_FILES: AssignmentFile[];
}

export enum AssignmentStatus {
  NOT_DONE = "NOT_DONE",
  SUBMITTED = "SUBMITTED",
  GRADED = "GRADED",
  SUBMITTED_TOO_LATE = "SUBMITTED_TOO_LATE",
}

export type MulterFile = {
  fieldname: string;
  originalname: string;
  encoding: string;
  mimetype: string;
  destination: string;
  filename: string;
  url: string;
  size: number;
};
