import { useAxiosPrivate } from "api";
import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { FunctionalityAPIEndpoints } from "types";

// Generated by https://quicktype.io

export interface DashbordInfo {
  students: Student[];
  teachers: Teacher[];
}

export interface Student {
  STUDENT_ID: number;
  PUBLIC_NAME: string;
  PHOTO_URL: string;
}
export interface Teacher {
  TEACHER_ID: number;
  EMPLOYEE_ID: number;
  PUBLIC_NAME: string;
  PHOTO_URL: string;
  SUBJECTS: Subjects;
}

export enum Subjects {
  Danish = "Danish",
}

const MainSubPage = () => {
  const [dashboardData, setDashboardData] = useState<DashbordInfo | null>(null);
  const { students, teachers } = dashboardData || {};
  const axios = useAxiosPrivate();
  const navigate = useNavigate();
  useEffect(() => {
    axios
      .get(FunctionalityAPIEndpoints.FUNCTIONALITY + "admin/app")
      .then((res) => setDashboardData(res.data))
      .catch((err) => console.log(err));
  }, []);

  return (
    <section className="w-full h-full overflow-y-auto p-10 flex flex-col space-y-4">
      <div className="flex justify-between mb-2">
        <h1 className="font-bold text-2xl">Dashboard</h1>
        <div className="w-36 h-10 bg-primary"></div>
      </div>

      <article className="overflow-y-auto max-h-96 bg-white p-5 rounded-md max-w-5xl">
        <h1 className="text-xl font-semibold pb-4">Teachers</h1>
        {teachers &&
          teachers.map(({ PHOTO_URL, TEACHER_ID, PUBLIC_NAME }, index) => (
            <li
              className="grid grid-cols-5 p-4 border-t-input-border border-t-2 w-full last:border-b-2"
              key={index}
            >
              <img
                src={PHOTO_URL}
                className="h-14 w-14 object-cover border-2 border-primary rounded-full col-span-1 flex items-center justify-center"
                alt={`Profile picture of student ID: ${TEACHER_ID}`}
              />
              <div className="col-span-3 flex font-semibold space-x-2 items-center justify-start">
                <p>#{TEACHER_ID}</p>
                <p>{PUBLIC_NAME}</p>
              </div>
              <button
                onClick={() => navigate(`teacher/${TEACHER_ID}`)}
                className="border border-primary font-semibold rounded-lg py-2 col-span-1"
              >
                Check profile
              </button>
            </li>
          ))}
      </article>
      <article className="overflow-y-auto max-h-96 bg-white p-5 rounded-md max-w-5xl">
        <h1 className="text-xl font-semibold pb-4">
          Students from Schoolsystem
        </h1>
        {students &&
          students.map(({ PHOTO_URL, STUDENT_ID, PUBLIC_NAME }, index) => (
            <li
              className="grid grid-cols-5 p-4 border-t-input-border border-t-2 w-full last:border-b-2"
              key={index}
            >
              <img
                src={PHOTO_URL}
                className="h-14 w-14 object-cover border-2 border-primary rounded-full col-span-1 flex items-center justify-center"
                alt={`Profile picture of student ID: ${STUDENT_ID}`}
              />
              <div className="col-span-3 flex font-semibold space-x-2 items-center justify-start">
                <p>#{STUDENT_ID}</p>
                <p>{PUBLIC_NAME}</p>
              </div>
              <button
                onClick={() => navigate(`student/${STUDENT_ID}`)}
                className="border border-primary font-semibold rounded-lg py-2 col-span-1"
              >
                Check profile
              </button>
            </li>
          ))}
      </article>
    </section>
  );
};

export default MainSubPage;
